apiVersion: apps/v1
kind: Deployment
metadata:
  name: tk-mart

spec:
  replicas: 2

  selector:
    matchLabels:
      app: tk-mart

  template:
    metadata:
      labels:
        app: tk-mart

    spec:
      containers:
        - name: tk-mart
          image: shamona/tk-mart:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80